### PR TITLE
Release 6.0.0

### PR DESCRIPTION
**Pull request by jdlrobson**
The new version provides the ability to declare dependencies
to MediaWiki internals explicitly rather than enable everything.

### CODE REVIEW

**Comment by jdlrobson** [comment]
See https://gerrit.wikimedia.org/r/523793 and https://gerrit.wikimedia.org/r/521303 for usages

**Comment by niedzielski** [comment]
Hey @kostajh and @egardner! We're trying to dry up some of this test code in the hopes that it could be useful by other repos. Feel free to comment or open new PRs as you like. I think we're hoping to merge this one soon.

**Review by kostajh — APPROVED** [review]
Seems OK to me, although if there are issues with this release I'm not sure I'd catch them as I've not spent too much time with these tools.

**Comment by kostajh** [comment]
@jdlrobson looks like this release still need to be published at https://www.npmjs.com/package/@wikimedia/mw-node-qunit

**Comment by jdlrobson** [comment]
Yehh. I think Stephen is the only one who can publish it to npm and Stephen is out until November.

**Comment by santhoshtr** [comment]
If you can give me your npm username(in email) I can add to wikimedia organization in npm.

**Pull request merged**
